sudo: required
language: node_js
node_js:
  - '8'
services:
  - mongodb
before_install:
  - chmod +x cron.sh
  - sudo echo 'travis' >> /etc/cron.allow
install:
  - npm i npminstall && npminstall
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
