sudo: required
language: node_js
node_js:
  - '8'
services:
  - mongodb
before_install:
  - sudo apt-get install graphicsmagick
  - sudo apt-get install tesseract-ocr
  - sudo apt-get install libtesseract-dev
  - chmod +x cron.sh
install:
  - npm i npminstall && npminstall
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
